const express = require('express');
const app = express();
app.use(express.json());
app.use(cors());
app.use('/api/productos', productsRoutes);
app.use('/api/usuarios', usersRoutes);
app.use('/api/comisiones', commissionRoutes);
app.use('/api/ordenes'), ordersRoutes;
app.use('/api/tiendas', storeRoutes);
app.use('/api/login'), authRoutes;